"""Generate small binary-pattern fixtures using Python's standard library."""
from pathlib import Path
import struct
import math

def lua_bytes(data):
    return '"' + ''.join(f'\\{byte:03}' for byte in data) + '"'

def number(value):
    if value == 0 and struct.pack('>d', value)[0] == 128:
        return '(-1 / math.huge)'
    return repr(value)

tests = ["-- Generated by generate_numeric_tests.py; Python is the byte-level oracle.\nlocal test=require('test.ljtest')\n"]
for width in (8, 16, 24, 32, 40, 48):
    for signed in (False, True):
        lo = -(1 << (width - 1)) if signed else 0
        hi = (1 << (width - int(signed))) - 1
        values = sorted({lo, lo + 1, 0, 1, hi - 1, hi} | ({-1} if signed else set()))
        for endian in ('big', 'little'):
            alias = ('le_' if endian == 'little' else '') + ('s' if signed else 'u') + str(width)
            rows = ',\n'.join('{' + str(v) + ',' + lua_bytes(v.to_bytes(width // 8, endian, signed=signed)) + '}' for v in values)
            tests.append(f"""
test.it('numeric oracle {alias}',function(t)
  local fixtures={{{rows}}}
  for pass=1,80 do for _,fixture in ipairs(fixtures) do
    local value,expected=fixture[1],fixture[2]
    local actual=@b{{value<{alias}>}}
    t.equal(actual,expected)
    local @b{{decoded<{alias}>}}=expected
    t.equal(decoded,value)
  end end
  local values={{{','.join(map(str, values))}}}
  local vector=@b{{values<{alias}[{len(values)}]>}}
  local @b{{decoded<{alias}[{len(values)}]>}}=vector
  t.deep_equal(decoded,values)
  for _,invalid in ipairs({{{lo-1},{hi+1},0.5}}) do
    t.raises(function() return @b{{invalid<{alias}>}} end,'does not fit')
  end
end)
""")

for width, code in ((16, 'e'), (32, 'f'), (64, 'd')):
    values = [0.0, -0.0, 1.25, -1.25, 1.1, -1.1, 2**-14, 2**-24, 65504.0]
    if width == 16:
        # Ties, exponent carries, underflow, and values separated in binary64
        # but merged by an intermediate binary32 conversion.
        for exponent in range(-24, 16):
            power = 2.0 ** exponent
            for value in (power, power * (1 - 2**-12), power * (1 + 2**-11)):
                values.extend((value, -value, math.nextafter(value, 0.0),
                               math.nextafter(value, math.inf)))
        for value in (1.9999, 2**-25, 2**-26, 1e-300, 65519.0):
            values.extend((value, -value, math.nextafter(value, 0.0),
                           math.nextafter(value, math.inf)))
    if width == 32:
        values += [2**-149, 2**-126, 16777217.0]
    if width == 64:
        values += [2**-100, 2**100, 9007199254740991.0]
    for endian, prefix in (('big', '>'), ('little', '<')):
        alias = ('le_' if endian == 'little' else '') + 'f' + str(width)
        rows = []
        for value in values:
            data = struct.pack(prefix + code, value)
            expected = struct.unpack(prefix + code, data)[0]
            rows.append('{' + number(value) + ',' + lua_bytes(data) + ',' + number(expected) + '}')
        rows_lua = ',\n'.join(rows)
        tests.append(f"""
test.it('numeric oracle {alias}',function(t)
  local fixtures={{
{rows_lua}
  }}
  for pass=1,80 do for _,fixture in ipairs(fixtures) do
    local value,expected=fixture[1],fixture[2]
    local actual=@b{{value<{alias}>}}
    t.equal(actual,expected)
    local @b{{decoded<{alias}>}}=expected
    t.equal(decoded,fixture[3])
    if decoded == 0 then t.equal(1/decoded,1/fixture[3]) end
  end end
end)
""")

Path(__file__).with_name('binary_numeric_test.lua').write_text(''.join(tests))
print('Generated 30 numeric test groups with independent byte fixtures.')
